from abc import ABC, abstractmethod


class VpnPanelError(Exception):
    def __init__(self, code: str, message_fa: str, detail: str | None = None):
        super().__init__(detail or message_fa)
        self.code = code
        self.message_fa = message_fa
        self.detail = detail


class VpnPanelAdapter(ABC):
    @abstractmethod
    async def test_connection(self): ...
    @abstractmethod
    async def list_inbounds(self): ...
    @abstractmethod
    async def create_client(self, payload: dict): ...
    @abstractmethod
    async def update_client(self, payload: dict): ...
    @abstractmethod
    async def renew_client(self, payload: dict): ...
    @abstractmethod
    async def add_traffic(self, payload: dict): ...
    @abstractmethod
    async def reset_traffic(self, payload: dict): ...
    @abstractmethod
    async def disable_client(self, payload: dict): ...
    @abstractmethod
    async def enable_client(self, payload: dict): ...
    @abstractmethod
    async def delete_client(self, payload: dict): ...
    @abstractmethod
    async def get_client_usage(self, payload: dict): ...
    @abstractmethod
    async def get_config_link(self, payload: dict): ...
    @abstractmethod
    async def get_subscription_link(self, payload: dict): ...
    @abstractmethod
    async def reset_subscription_link(self, payload: dict): ...
