from abc import ABC, abstractmethod


class VpnPanelAdapter(ABC):
    @abstractmethod
    async def test_connection(self): ...
    @abstractmethod
    async def list_inbounds(self): ...
    @abstractmethod
    async def create_client(self, inbound_id: int, client: dict): ...
    @abstractmethod
    async def update_client(self, client_id: str, payload: dict): ...
    @abstractmethod
    async def renew_client(self, client_id: str, expiry_time_ms: int): ...
    @abstractmethod
    async def add_traffic(self, client_id: str, bytes_amount: int): ...
    @abstractmethod
    async def reset_traffic(self, email: str): ...
    @abstractmethod
    async def disable_client(self, client_id: str): ...
    @abstractmethod
    async def enable_client(self, client_id: str): ...
    @abstractmethod
    async def delete_client(self, inbound_id: int, client_id: str): ...
    @abstractmethod
    async def get_client_usage(self, email: str): ...
    @abstractmethod
    async def get_config_link(self, inbound_id: int, email: str): ...
    @abstractmethod
    async def get_subscription_link(self, sub_id: str): ...
    @abstractmethod
    async def reset_subscription_link(self, inbound_id: int, email: str): ...
